server:
  port: 80
  server:
    error:
      whitelabel:
        enabled: false
  spring:
    mvc:
      throw-exception-if-no-handler-found: true
    resources:
      add-mappings: false
spring:
  datasource:
    url: [PRIVATE]
    username: [PRIVATE]
    password: [PRIVATE]
  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  cloud:
    gcp:
      credentials:
        location: 0
facebook:
  appId: [PRIVATE]
  appSecret: [PRIVATE]
google:
  appId: [PRIVATE]
  appSecret: [PRIVATE]
github:
  appId: [PRIVATE]
  appSecret: [PRIVATE]
gcs:
  bucket-name: [PRIVATE]
  media-folder-name: [PRIVATE]
